name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Mambaforge Python 3.7
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: myenv
        python-version: 3.7
        use-mamba: true
    - name: Compile content
      run: |
        cd content
        make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./content/build/html/

# https://github.com/marketplace/actions/github-pages-action